module.exports = [
  {name: "exclusiveMinimum", test: require("../extras/exclusiveMinimum.json")},
  {name: "exclusiveMaximum", test: require("../extras/exclusiveMaximum.json")},
  {name: "contains", test: require("../extras/contains.json")},
  {name: "const", test: require("../extras/const.json")},
  {name: "$data/uniqueItems", test: require("../extras/$data/uniqueItems.json")},
  {name: "$data/required", test: require("../extras/$data/required.json")},
  {name: "$data/pattern", test: require("../extras/$data/pattern.json")},
  {name: "$data/multipleOf", test: require("../extras/$data/multipleOf.json")},
  {name: "$data/minimum", test: require("../extras/$data/minimum.json")},
  {name: "$data/minProperties", test: require("../extras/$data/minProperties.json")},
  {name: "$data/minLength", test: require("../extras/$data/minLength.json")},
  {name: "$data/minItems", test: require("../extras/$data/minItems.json")},
  {name: "$data/maximum", test: require("../extras/$data/maximum.json")},
  {name: "$data/maxProperties", test: require("../extras/$data/maxProperties.json")},
  {name: "$data/maxLength", test: require("../extras/$data/maxLength.json")},
  {name: "$data/maxItems", test: require("../extras/$data/maxItems.json")},
  {name: "$data/format", test: require("../extras/$data/format.json")},
  {name: "$data/exclusiveMinimum", test: require("../extras/$data/exclusiveMinimum.json")},
  {name: "$data/exclusiveMaximum", test: require("../extras/$data/exclusiveMaximum.json")},
  {name: "$data/enum", test: require("../extras/$data/enum.json")},
  {name: "$data/const", test: require("../extras/$data/const.json")},
  {name: "$data/absolute_ref", test: require("../extras/$data/absolute_ref.json")},
]
